Use URI template instead of path as a part of measurement name
Webinterpret/falcon-telegraf-middleware pull request #10
Opened 2018-10-09 15:10 UTC by matee911

2018-10-09 15:18 UTC, NicholasSimons commented on falcon_telegraf/base.py
> +        return self._metric_name_prefix + (req.uri_template or req.path)
And if req.path is not present either? We just log self._metric_name_prefix

2018-10-09 15:33 UTC, NicholasSimons commented
+1

2018-10-10 08:55 UTC, NicholasSimons approved these changes
Still +1.  Willing to test if necessary.

2018-10-10 20:10 UTC, ekamil requested changes
Please clear up wording in readme and keep backwards compat. (detailed comments follow)

2018-10-10 20:10 UTC, ekamil commented on README.md
> +Executes *after* `on-*` method was called and adds context data. Because of this you can add custom tags.
> was called and adds context data
The middleware adds context data?

2018-10-10 20:10 UTC, ekamil commented on falcon_telegraf/__init__.py
>      'Timer',
Maybe instead mark `LogHitsContextAware` as deprecated and (log.warn in init) and apart from that remove the body of that class. This way you provide a pain-free method of upgrade with this highly beneficial change.

2018-10-11 09:49 UTC, merged